### ISSUE TITLE
numpy in setup.py 

### ISSUE THREAD

**Issue by kspeng** [DrSleep/DenseTorch#2]
Just found that numpy needs to be included in setup.py and add include explicitly to avoid install error. If possible, please update setup.py.

--
from setuptools import setup, Extension
import numpy # <<==
with open('requirements.txt') as f:
    requirements = f.read().splitlines()

setup(
    name="densetorch",
    version="0.0.1",
    author="Vladimir Nekrasov",
    author_email="nekrasowladimir.at.gmail.com",
    description="Light-Weight PyTorch Wrapper for dense per-pixel tasks.",
    url="https://github.com/drsleep/densetorch",
    include_dirs=[numpy.get_include()],   # <<==
    packages=["densetorch"],
    setup_requires=[
        'setuptools>=18.0',
        'cython'],
    install_requires=requirements,
    ext_modules=[
        Extension('densetorch.engine.miou', sources=['./densetorch/engine/miou.pyx'])],
    classifiers=("Programming Language :: Python :: 3"),
    zip_safe=False)

**Comment by DrSleep** [comment]
thanks, fixed
