### ISSUE TITLE
Download the NYUDv2 dataset with segmentation and depth masks

### ISSUE THREAD

**Issue by wwwjn** [DrSleep/DenseTorch#4]
Hi,
When I want to download NYUDv2 with segmentation and depth masks using the link provided (https://cloudstor.aarnet.edu.au/plus/s/pQY2sgg4fffGUYy), I can't find the file and the link seems out of date. Could you please check and update the link to the dataset?

**Comment by wwwjn** [comment]
Thanks a lot for your help!

**Comment by DrSleep** [comment]
Thanks for letting me know about that! Not sure why it happened.

Could you please try this one instead: https://cloudstor.aarnet.edu.au/plus/s/XJKtmOKcTEnANZt ?

**Comment by wwwjn** [comment]
Thanks a lot for your reply and help! This new link works well!
