### ISSUE TITLE
Run pip install -e. An error occurred, please help me

### ISSUE THREAD

**Issue by fuxiao567** [DrSleep/DenseTorch#8]
Building wheels for collected packages: python2
  Building wheel for python2 (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/d1/6a/52/2ea03062735c314798c8c5ac3da63271888638d2f4fed6d4bd
Successfully built python2
Installing collected packages: python2, densetorch
  Running setup.py develop for densetorch
    ERROR: Complete output from command /usr/bin/python3.6 -c 'import setuptools, tokenize;__file__='"'"'/root/data/densetorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing densetorch.egg-info/PKG-INFO
    writing dependency_links to densetorch.egg-info/dependency_links.txt
    writing requirements to densetorch.egg-info/requires.txt
    writing top-level names to densetorch.egg-info/top_level.txt
    reading manifest file 'densetorch.egg-info/SOURCES.txt'
    writing manifest file 'densetorch.egg-info/SOURCES.txt'
    running build_ext
    skipping './densetorch/engine/miou.c' Cython extension (up-to-date)
    building 'densetorch.engine.miou' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -I/usr/include/python3.6m -c ./densetorch/engine/miou.c -o build/temp.linux-x86_64-3.6/./densetorch/engine/miou.o
    ./densetorch/engine/miou.c:14:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python3.6 -c 'import setuptools, tokenize;__file__='"'"'/root/data/densetorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /root/data/densetorch/

**Comment by DrSleep** [comment]
You need to have python3-dev installed.
Read more here: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by fuxiao567** [comment]
> 您需要安装python3-dev。
> 在此处阅读更多信息：[https](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory) : [//stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory)
Thank you very much.
