### ISSUE TITLE
Evaluation scripts of multi-task tight-weight refineNet.

### ISSUE THREAD

**Issue by fuxiao567** [DrSleep/DenseTorch#9]
would you like to share the evaluation scripts of multi-task tight-weight refinenet?Thank you.

**Comment by DrSleep** [comment]
you can run validation as in the example here: https://github.com/DrSleep/DenseTorch/blob/master/examples/multitask/train.py#L83-L90

**Comment by fuxiao567** [comment]
Would you provide a more detailed test.py script to evaluate the test set? Thank you

**Comment by DrSleep** [comment]
what do you mean by "a more detailed script"? 
The provided example does both training and testing. If you comment out the training part (e.g, [line 82](https://github.com/DrSleep/DenseTorch/blob/master/examples/multitask/train.py#L82)), it will only run the testing part

**Comment by fuxiao567** [comment]
Thank you for helping me solve this problem.
